import test from "node:test";
import assert from "node:assert/strict";

import { validateAiQuery } from "../src/ai/services/ai-query.service.js";

const buildQuery = (body, userId = "user-123") => validateAiQuery(body, userId);

test("normal financial question structure is accepted", () => {
  const query = buildQuery({
    entity: "expenses",
    operation: "sum",
    aggregate_field: "amount",
    filters: { date_from: "2026-09-01", date_to: "2026-09-30" },
    limit: 20,
  });

  assert.equal(query.entity, "expenses");
  assert.equal(query.operation, "sum");
  assert.equal(query.where.user_id, "user-123");
});

test("keyword search question is accepted and case-insensitive", () => {
  const query = buildQuery({
    entity: "expenses",
    operation: "count",
    filters: { text_contains: "SAMOSA" },
  });

  assert.equal(query.where.user_id, "user-123");
  assert.ok(query.where.text);
});

test("Tirupati sum question is accepted", () => {
  const query = buildQuery({
    entity: "expenses",
    operation: "sum",
    aggregate_field: "amount",
    filters: { title_contains: "Tirupati" },
  });

  assert.equal(query.entity, "expenses");
  assert.equal(query.operation, "sum");
});

test("person/debt question is accepted", () => {
  const query = buildQuery({
    entity: "borrowed",
    operation: "sum",
    aggregate_field: "amount",
    filters: { person_name: "Ajay" },
  });

  assert.equal(query.entity, "borrowed");
  assert.equal(query.where.user_id, "user-123");
});

test("birthday question is accepted", () => {
  const query = buildQuery({
    entity: "birthdays",
    operation: "list",
    filters: { date_from: "2026-09-01", date_to: "2026-09-07" },
    limit: 10,
  });

  assert.equal(query.entity, "birthdays");
  assert.equal(query.where.user_id, "user-123");
});

test("invalid query generated by LLM is rejected", () => {
  assert.throws(() => {
    buildQuery({
      entity: "passwords",
      operation: "list",
      filters: { text_contains: "secret" },
    });
  }, /forbidden|passwords/i);
});

test("attempt to access another user is rejected", () => {
  assert.throws(() => {
    buildQuery(
      {
        entity: "expenses",
        operation: "list",
        user_id: "another-user",
      },
      "user-123",
    );
  }, /user_id/i);
});

test("forbidden entity is rejected", () => {
  assert.throws(() => {
    buildQuery(
      {
        entity: "users",
        operation: "list",
      },
      "user-123",
    );
  }, /forbidden|users/i);
});

test("no matching data is handled as empty result", () => {
  const query = buildQuery(
    {
      entity: "expenses",
      operation: "list",
      filters: { text_contains: "nonexistentitemxyz" },
    },
    "user-123",
  );

  assert.equal(query.where.user_id, "user-123");
  assert.ok(query.where.text);
});

test("LLM failure is gracefully handled", () => {
  assert.throws(() => {
    validateAiQuery(
      {
        entity: "expenses",
        operation: "sum",
        filters: { raw_sql: "SELECT 1" },
      },
      "user-123",
    );
  }, /sql|unsafe/i);
});
